# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            배하람
tagline:          'A Jekyll theme'
description:      '<small>"Talk is cheap.<br>Show me the code"<br>Linus Torvalds<br><a href="https://github.com/baeharam/TIL">TIL</a>을 위한 블로그.</small>'
url:              https://baeharam.github.io
locale:          	'ko'
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
disqus:
   shortname: baeharam
google_analytics: UA-121633022-1
author:
  name:           '배하람'

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

excerpt_separator: ""
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/baeharam/baeharam.github.io